name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          yarn --frozen-lockfile
          yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'ike1z.github.io/docs'
